### ISSUE TITLE
Allow configuration of server in 

### ISSUE THREAD

**Issue by maxnoe** [SonarSource/sonarqube-scan-action#89] opened 2023-11-17 09:15 UTC
We had our server configured in our project config file:

```
❯ cat sonar-project.properties
sonar.host.url=https://...
```

But the action complained about needing it via the `SONAR_HOST_URL` env variable.

Is there a technical reason for this? Why can't it be set in the config file?

**Comment by csaba-feher-sonarsource** [comment] 2024-05-22 12:11
This seems to be a duplicate off
https://github.com/SonarSource/sonarqube-scan-action/issues/53

**Comment by henryju** [comment] 2024-05-23 05:40
Ticket created: https://sonarsource.atlassian.net/browse/SQSCANGHA-31

**Closed by henryju** 2024-05-23 05:40 UTC
